### ISSUE TITLE
Question Angular 6 support

### ISSUE THREAD

**Issue by anvial** [bohoffi/ngx-localstorage#10]
Hello, 

I've problem with my project production install 'ng bluild --prod'. 

Here is the error: 
![image](https://user-images.githubusercontent.com/1950326/40486447-f573a48a-5f69-11e8-8ffc-e77596e903ba.png)

Have any ideas?

**Comment by anvial** [comment]
May be this warnings during non-prod-build will help...

![image](https://user-images.githubusercontent.com/1950326/40501563-e520e3a0-5f90-11e8-8e58-57a173e44177.png)

**Comment by bohoffi** [comment]
Relates to angular/angular#23609 so we have to wait for them to fix it. I will close this issue.
