### ISSUE TITLE
Angular 6

### ISSUE THREAD

**Issue by krivochenko** [bohoffi/ngx-localstorage#12]
**Describe the bug**
ERROR in node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
node_modules/ngx-localstorage/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

**To Reproduce**
1. Generate new app using CLI 6.1.0
2. Install this package
3. npm run start

**Expected behavior**
No error

**Comment by bohoffi** [comment]
Just by installing the package the app would not crash like in this quick example:
https://stackblitz.com/edit/angular-yq38k3

Could you please provide a minimal repo to reproduce the issue?

**Comment by alexandremoore** [comment]
@krivochenko as a workaround, you can add this to your tsconfig.json, under compilerOptions:
`"paths": {
      "@angular/*": ["node_modules/@angular/*"]
    }`

**Comment by bohoffi** [comment]
@alexandremoore you seem to know this issue. Does it originate from Angular or is there something wrong with my package?

**Comment by alexandremoore** [comment]
@bohoffi, long story short, this is mainly because you include angular dependencies within your library. They should be set as peer dependencies instead.

**Comment by bohoffi** [comment]
@alexandremoore that's not the problem. The library has its own package.json file (located under projects/ngx-localstorage) and angular is listed as peer dependency.

**Comment by alexandremoore** [comment]
@bohoffi I have v2.0.1 installed and here's the dependencies listed in package.json:
` "dependencies": {
    "@angular/animations": "^5.2.0",
    "@angular/cdk": "^5.2.2",
    "@angular/common": "^5.2.0",
    "@angular/compiler": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/forms": "^5.2.0",
    "@angular/http": "^5.2.0",
    "@angular/material": "^5.2.2",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "core-js": "^2.4.1",
    "rxjs": "^5.5.6",
    "zone.js": "^0.8.19"
  },`

**Comment by bohoffi** [comment]
@alexandremoore damn it, you're right. I'm Sorry. If I find the time the next days I will release v2.1.0 which will fix this. 🤦‍♂️

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by alexandremoore** [comment]
@bohoffi No problem. Glad I could help.

**Comment by bohoffi** [comment]
Closed with 41da1bd
