### ISSUE TITLE
NgxLocalStorageModule.forRoot({prefix: 'demo'})   can not work

### ISSUE THREAD

**Issue by chen024** [bohoffi/ngx-localstorage#21]
module code:
`
....
@NgModule({
  declarations: [JobComponent],
  imports: [
    NgxLocalStorageModule.forRoot({prefix: 'demo'})
  ],
  exports: [JobComponent]
})
....`

component code:
`
....
  ngOnInit() {
    this.lss.set("myjob", 'IT');
    console.log(this.lss.count());
    this.boundText = "eee";
  }

  @ngxLocalStorage({ key: 'txt1' })
  boundText: string;
....`

in my chrome browser local storage have two value with no prefix，（myjob：IT，txt1：eee），
but how an I get two value with prefix(demo) that I declare in my module? （demo_myjob：IT，demo_txt1：eee）

**Comment by bohoffi** [comment]
@chen024 could you please provide some further information like the used library version?

Using the provided issue template would provide my with nearly all necessary information.

**Comment by Ne4istb** [comment]
@bohoffi I have the same issue after upgrade to version 2.4.0

I have next configuration in app.module:
```ts
NgxLocalStorageModule.forRoot({ prefix: 'my', allowNull: false })
```

Next usage:
```ts
this.storage.set('key', 'value');
```
With v2.3.0 the record with name 'my_key' is created.
With v2.4.0 the record with name 'key' is created.
