### ISSUE TITLE
How to set object for key?

### ISSUE THREAD

**Issue by sh977218** [bohoffi/ngx-localstorage#23]
Is there any way I can do 
`this.localStorageService.set('myKey',{myValue: 1 })`?

**Comment by bohoffi** [comment]
@sh977218 as I didn't want to limit the librarys users to only one way of serialization it's up to you.
You could use `JSON.stringify()` for example to create the serialized object and `JSON.parse()` to get it back as an object.

Does this answer your question?

**Comment by sh977218** [comment]
@bohoffi  Thanks for the quick response. I guess I can do that. Still It would be nice to let value to be any.

**Comment by bohoffi** [comment]
I can understand your request and openen a new feature request #24 to provide a default (de)serializer (using the mentioned `JSON.stringify()/JSON.parse()`) which will be used when omitting the (de)serializer paramter.
