### ISSUE TITLE
Event Stream not firing

### ISSUE THREAD

**Issue by rdsmartins** [bohoffi/ngx-localstorage#39]
Hi All,

For some reason, I'm not able to make the stream event work. Please see below the snippet :

`
this.es.stream.subscribe(e => {
      console.log("events: ", e);
    });

    setTimeout(() => {
      this._storageService.set("demo-key-2", {
        id: 1,
        name: "John Doe"
      });
    }, 5000);
`

**Comment by bohoffi** [comment]
@rdsmartins Could you please provide a reproducible example (e.g. via stackblitz)?

**Comment by rdsmartins** [comment]
Hi @bohoffi, Thanks for the reply. 
After further investigations, I found out that the event is only going to be fired after changes in ANOTHER browser window. So in plain words, for testing it, we need to have at least 2 windows opened to see the event being fired. 

Thanks again.
