### ISSUE TITLE
I think this is incorrect

### ISSUE THREAD

**Issue by pookdeveloper** [bohoffi/ngx-localstorage#40]
In this case:

https://github.com/bohoffi/ngx-localstorage/blob/df6afcd9e25e84e32fed2ecdc27b0e3d5a12d6e2/libs/ngx-localstorage/src/lib/services/ngx-localstorage.service.ts#L113

It will be:
`this.remove(key, prefix);`

Thanks

**Comment by bohoffi** [comment]
Hey @pookdeveloper, thank you very much for pointing out.

I'll fix that later today.
