### ISSUE TITLE
Is ngx-localstorage compatible with Angular Universal? 

### ISSUE THREAD

**Issue by ermamud** [bohoffi/ngx-localstorage#45]
I am using the latest version of Angular 12 with this package. For regular web implementation, it works great but when trying to do Server Rendering with Angular Universal, I am getting the next error:
```
/Users/*/Documents/Development/*/*/*/dist/web/server/main.js:203702
    storage: localStorage,
             ^

ReferenceError: localStorage is not defined
```
any idea why is this happening?

Thanks

**Comment by bohoffi** [comment]
Hey @ermamud that's because `localstorage` is part of the browsers API which aren't available when an app is prerendered on the server.

There're some workarounds on the internet but for now the library is built to be used in standard web applications executed in the browser.

**Comment by ermamud** [comment]
Thanks, already found a solution that is working fine.  Here it is the link:
https://www.thecodehubs.com/how-to-solve-localstorage-is-not-defined-in-angular-11/

I was hoping there was a cleaner solution, this one feels like hack 👍 

Thank you,
Ernesto
