### ISSUE TITLE
Error handling when third-party cookies are disabled.

### ISSUE THREAD

**Issue by rvab** [bohoffi/ngx-localstorage#46]
I am developing an application where access to `localStorage` is mandatory. In case the user has blocked third-party cookies, the screen shows the steps to enable them. Currently, I'm getting an error as `Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.` during application bootstrap. Due to this, the user cannot proceed further and sees a blank screen which is not a good UX.

**Describe the solution you'd like**
1. The library should handle errors gracefully when the user has blocked third-party cookies.
2.  Expose a method to check if `localStorage` is supported or not.

**Comment by bohoffi** [comment]
Hi @rvab 
I do understand your wishes for this library but

1. 'graceful' is a very relative term and with implementing any specific error handling logic I may restrict the functionality of apps already using this library by 'hiding' errors. The purpose of the lib is wrapping the access combined with features like auto prefixing and **not** taking responsibility for application UX
2. as stated in point 1 the libs purpose is access wrapping. The way checking the availability can differ depending on the browsers you want to support. As the lib sticks to web standards I can't and I won't implement an availability check for every browser out there + maintaining these checks

**Comment by rvab** [comment]
Hi @bohoffi,
Do you recommend any workaround for this?

**Comment by bohoffi** [comment]
Hey @rvab 
There're a lot of possible implementations for checking general availability of `localstorage` out there on the web like on the Mozilla MDN. I recommend implementing such check yourself before using this lib for accessing the storage.
