### ISSUE TITLE
Ivy update

### ISSUE THREAD

**Issue by Lokomojo** [bohoffi/ngx-localstorage#50]
Processing legacy "View Engine" libraries:

- ngx-localstorage [es2015/esm2015] (git+https://github.com/bohoffi/ngx-localstorage.git)
Encourage the library authors to publish an Ivy distribution.

Consider yourself encouraged :)

**Comment by bohoffi** [comment]
Hey @TomMettam 
v4.0.0 is in preparation for a while now jumping straight from Angular v10 to v14 but it'll introduce some breaking changes.

To cut waiting time I'll bake another v3 (v3.5.0) fulfilling your wish of encouraging me :)

**Comment by bohoffi** [comment]
@TomMettam v3.5.0 is available via npm now - built with Ivy using Angular 13

**Comment by Lokomojo** [comment]
Thank you! <3
