### ISSUE TITLE
Incompatible peer dependency to "rxjs" (requires "~7.5.0", would install "7.8.0")

### ISSUE THREAD

**Issue by JulienAtSimplon** [bohoffi/ngx-localstorage#58]
**Describe the bug**
Incompatible peer dependency to "rxjs" (requires "~7.5.0", would install "7.8.0")

**To Reproduce**
1. `ng new AngularProjectV15`
2. `npm i ngx-localstorage`
3. See error

**Expected behavior**
Compatible peer dependency to rxjs@7.8.0

**Version information (please complete the following information):**
 - Module 5.0.0
 - Angular 15.2.6

**Comment by bohoffi** [comment]
Hi @JulienAtSimplon 

could you send the (peer)dependencies of your app please?
`ngx-localstorage` does not have any fixed `rxjs` version as dependencies as you can see in the packages [`package.json`](https://github.com/bohoffi/ngx-localstorage/blob/develop/libs/ngx-localstorage/package.json):
```json
{
  "name": "ngx-localstorage",
  "version": "5.0.0",
  "peerDependencies": {
    "@angular/common": "^15.0.0",
    "@angular/core": "^15.0.0"
  },
  "dependencies": {
    "tslib": "^2.3.0"
  }
}
```

**Comment by Boris-Bodin** [comment]
This issue should be corrected with the PR: https://github.com/bohoffi/ngx-localstorage/pull/59

**Comment by bohoffi** [comment]
@JulienAtSimplon thanks to @Boris-Bodin the release `5.1.0` updates the Angular version compatibility
