### ISSUE TITLE
LocalStorage Changes from other window tabs are not detected

### ISSUE THREAD

**Issue by chbuck** [bohoffi/ngx-localstorage#6]
Please listen to 'storage' events on the window object to detect changes made in other browser tabs

**Comment by bohoffi** [comment]
@chbuck this seems to be some kind of reactive extension. I will take a look at it but feel free to contribute if you already have some ideas.

**Comment by bohoffi** [comment]
@chbuck there is a first draft to play with (reactive support for decorator and directive):
https://stackblitz.com/edit/reactive-ngs-localstorage

**Comment by bohoffi** [comment]
A fix is available with release v2.0.0
