### ISSUE TITLE
[2.0.0] Error during Angular CLI (1.7.1) production build

### ISSUE THREAD

**Issue by anvial** [bohoffi/ngx-localstorage#8]
Hi,

I've an active warning during Angular CLI (1.7.1) production build

![image](https://user-images.githubusercontent.com/1950326/36537288-c0f49028-17e0-11e8-8269-d15ffe2191e3.png)

This issue come instead of warnings that was on ngx-localstorage version 1.2.0

**Comment by bohoffi** [comment]
Could you please provide the following information:
- Angular version
- a minimal [Stackblitz](https://stackblitz.com/) sample

**Comment by anvial** [comment]
- Angular version 5.2.6

With the sample it will be problematic. Cos the error raises during production build (`ng build -e=prod --prod` ). In non-prod mode everything is alright.

**Comment by bohoffi** [comment]
If you provide a sample on Stackblitz and share the link I could download the sample at home and run the production build myself.

**Comment by anvial** [comment]
I try to prepare example. But I don't know the reason of 'barrel'. So I'm not sure that the error will be reproduced in production build. But when I revert to version 1.2.0 (ngx-localstorage) everu this is OK (exept warnings =) ). 

https://stackblitz.com/edit/angular-1ucvxq

**Comment by anvial** [comment]
> Are you defining any of my services (LocalStorageService or StorageEventService) as a provider in one of your modules? (like in this issue: ionic-team/ionic-app-scripts#885)

Nope, only in imports... and then use the LocalStorageService in component cinstructor

**Comment by anvial** [comment]
Sorry, mistakenly closed the issue

**Comment by bohoffi** [comment]
Ok, I could reproduce the error using a newly created angular project (CLI 1.6.5).

I fixed the error with 50db69b4b58e61980dd80efd42bcf37b503166dd

**Comment by anvial** [comment]
Yes, 2.0.1 fix the problem.

Thank You!
