### ISSUE TITLE
Not working with Angular 6

### ISSUE THREAD

**Issue by MickL** [bohoffi/ngx-localstorage#9]
<img width="1136" alt="bildschirmfoto 2018-05-07 um 12 37 11" src="https://user-images.githubusercontent.com/5103210/39698032-6290245a-51f3-11e8-919b-2e8b82aa9215.png">

**Comment by bohoffi** [comment]
@MickL could you please provide a minimal repo to reproduce the error?

**Comment by bohoffi** [comment]
@MickL Your issues origin is not this library. The error message says that there is no _**add**_ property on **_LocalStorageService_** and this is correct.

I will close this issue.

**Comment by anvial** [comment]
I've likely error. 

![image](https://user-images.githubusercontent.com/1950326/40496917-97c4e744-5f83-11e8-8a68-a46437fe44d7.png)

I've no errors during dev-builds. 
The error happenes only in prod-builds.
